name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
    - name: make 
      run: make
    - name: make version
      run: make version
